package com.example.appapi.compose

enum class PageEnum {
    CREATION_ADHERENT,
    GESTION_ADHERENT,
    ADHERENT_DETAIL,
    MODIFICATION_ADHERENT,

    CREATION_PLONGEE,
    GESTION_PLONGEE,
    PLONGEE_DETAIL,
    MODIFICATION_PLONGEE
}
